schapp/urls.py
from django.urls import path
from .views import teachers, students

app_name = 'schapp'

urlpatterns = [
    # Teacher psths
    path('students', teachers.StudentListView.as_view(), name='all-students'),
    path('form1', teachers.form1_students, name='form1'),
    path('form2', teachers.form2_students, name='form2'),
    path('form3', teachers.form3_students, name='form3'),
    path('form4', teachers.form4_students, name='form4'),
    path('(?P<pk>\d+)/', teachers.student_detail, name='student-detail'),
    path('add-student', teachers.add_student, name='add-student'),
    path('(?P<pk>\d+)/student-update/', teachers.update_student, name='update-student'),
    path('(?P<pk>\d+)/student-delete/', teachers.delete_student, name='delete-student'),
    path('(?P<pk>\d+)/add-grade', teachers.add_grade, name='add-grade'),

    # Student paths
    path('profile', students.student_profile, name='student-profile'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', include('schapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schapp/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
DEPARTMENT = (
    ('english', 'English'),
    ('maths', 'Maths'),
    ('swahili', 'Swahili'),
    ('Biology', 'Biology'),
    ('Chemistry', 'Chemistry'),
    ('Physics', 'Physics'),
    ('Humanities', 'Humanities'),
    ('Grp4/5', 'Grp4/5'),
)

CLASS = (
    ('form 1', 'Form 1'),
    ('form 2', 'Form 2'),
    ('form 3', 'Form 3'),
    ('form 4', 'Form 4'),
)

YEAR = (
    ('2018', '2018'),
    ('2019', '2019'),
    ('2020', '2020'),
    ('2021', '2021'),
    ('2022', '2022'),
    ('2023', '2023'),

)


class Student(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    admission = models.BigIntegerField(unique=True)
    form = models.CharField(choices=CLASS, default='Form 1', max_length=6)
    house = models.CharField(max_length=50)
    club = models.CharField(max_length=50)
    #passport = models.ImageField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('schapp:teacher-index')


class Term(models.Model):
    name = models.CharField(max_length=10, unique=True)
    year = models.CharField(choices=YEAR, max_length=6, default=2018)

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=50)
    department = models.CharField(choices=DEPARTMENT, max_length=45, default='Maths')

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=20, unique=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT)
    department = models.CharField(choices=DEPARTMENT, max_length=45, default='Maths')

    def __str__(self):
        return self.name


class Grade(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    form = models.CharField(choices=CLASS, max_length=6, default='form 1')
    term = models.ForeignKey(Term, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT)
    cat = models.CharField(max_length=2)
    exam = models.CharField(max_length=3)
    remark = models.CharField(max_length=50)

    def __str__(self):
        return self.subject.name

schapp/forms.py
from django import forms
from .models import Student, Grade


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = '__all__'


class GradeForm(forms.ModelForm):

    class Meta:
        model = Grade
        exclude = ('student',)

schapp/views/students.py
from django.shortcuts import render
from django.views.generic import ListView
from ..models import Grade


def student_profile(request):
    grades = Grade.objects.all()
    return render(request, 'schapp/students/index.html', {'grades': grades})

schapp/views/teachers.py
from django.shortcuts import render, get_object_or_404
from ..forms import StudentForm, GradeForm
from ..models import Student, Subject
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView


class StudentListView(ListView):
    model = Student
    template_name = 'schapp/teachers/index.html'
    ordering = 'form'
    context_object_name = 'students'


def form1_students(request):
    students = Student.objects.filter(form='form 1')
    return render(request, 'schapp/teachers/index.html', {'students': students})


def form2_students(request):
    students = Student.objects.filter(form='form 2')
    return render(request, 'schapp/teachers/index.html', {'students': students})


def form3_students(request):
    students = Student.objects.filter(form='form 3')
    return render(request, 'schapp/teachers/index.html', {'students': students})


def form4_students(request):
    students = Student.objects.filter(form='form 4')
    return render(request, 'schapp/teachers/index.html', {'students': students})


# Saves student to DB
def save_student_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            students = Student.objects.filter(form='form 1')
            data['html_student_list'] = render_to_string('schapp/teachers/includes/partial-student-list.html',
                                                         {'students': students})
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


# Partial to re-use
def add_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
    else:
        form = StudentForm()
    return save_student_form(request, form, 'schapp/teachers/includes/partial-student-add.html')


def update_student(request, pk):
    s = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        form = StudentForm(request.POST, instance=s)
    else:
        form = StudentForm(instance=s)
    return save_student_form(request, form, 'schapp/teachers/includes/partial-student-update.html')


def delete_student(request, pk):
    s = get_object_or_404(Student, pk=pk)
    data = dict()
    if request.method == 'POST':
        s.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        students = Student.objects.filter(form='form 1')
        data['html_student_list'] = render_to_string('schapp/teachers/includes/partial-student-list.html', {
            'students': students
        })
    else:
        context = {'s': s}
        data['html_form'] = render_to_string('schapp/teachers/includes/partial-student-delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)


def save_grade_form(request, form, template_name, student):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            grade = form.save(commit=False)
            grade.student = student
            grade.save()
            data['form_is_valid'] = True
            students = Student.objects.all()
            data['html_student_list'] = render_to_string('schapp/teachers/includes/partial-student-list.html',
                                                         {'students': students})
        else:
            data['form_is_valid'] = False
    context = {'form': form, 'student': student}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def add_grade(request, pk):
    student = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        form = GradeForm(request.POST)
    else:
        form = GradeForm(instance=student.grade_set.first())
    return save_grade_form(request, form, 'schapp/teachers/includes/partial-grade-add.html', student)


"""
def add_grade(request, pk):
    student = get_object_or_404(Student, pk=pk)
    data = dict()
    if request.method == 'POST':
        form = GradeForm(request.POST or None)
        if form.is_valid():
            grade = form.save(commit=False)
            grade.student = student
            grade.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = GradeForm()
    context = {'form': form, 'student': student}
    data['html_form'] = render_to_string('schapp/teachers/includes/partial-grade-add.html',
                                         context, request=request)
    return JsonResponse(data)
"""


def student_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    subjects = Subject.objects.all()
    return render(request, 'schapp/teachers/student-details.html', {'student': student, 'subjects': subjects})

schapp/templates/schapp/teachers/index.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

{% load static %}
<link href="{% static 'schapp/teacher/css/custom.css' %}" rel="stylesheet" type="text/css">


<!--Javascript files -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script type="text/javascript" src="{% static 'schapp/teacher/js/teachers.js' %}"></script>


<div class="container">
    <div class="row">

        <!--Teacher info-->
        <div class="col-sm-3">
            <div class="panel panel-danger">
                <div class="panel-body">
                    <img src="{% static 'schapp/teacher/images/t.jpg' %}" class="img img-circle img-responsive" alt="No image to display" style="width: 150px;height: 150px;">

                    <div class="caption">
                        <h4>Name</h4>
                        <h5>Email</h5>
                        <h6>Department</h6>
                        <a href="" class="btn btn-info btn-sm"><i class="fas fa-edit"></i> </a>
                    </div>
                </div>
            </div>
        </div>
        <!--End Teacher section-->

        <!--Student info-->
        <div class="col-sm-9">
            <ul class="nav nav-tabs" style="margin: 2px;">
                <li class="active"><a href="{% url 'schapp:form1' %}">Form 1</a> </li>
                <li><a href="{% url 'schapp:form2' %}">Form 2</a> </li>
                <li><a href="{% url 'schapp:form3' %}">Form 3</a> </li>
                <li><a href="{% url 'schapp:form4' %}">Form 4</a> </li>
            </ul>


            <div class="panel panel-danger">
                <div class="panel-body">
                    <button type="button" class="btn btn-info js-add-student" data-url="{% url 'schapp:add-student' %}">Add Student</button>

                    <table class="table table-bordered"  id="student-table" style="margin: 2px;">
                        <thead>
                        <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Admission</th>
                        <th>Class</th>
                        <th>House</th>
                        <th>Club</th>
                        <th>Grades</th>
                        <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% include 'schapp/teachers/includes/partial-student-list.html' %}
                        </tbody>
                    </table>


                </div>
            </div>

        <!--Modal-->
                     <div class="modal fade" id="modal-student">
                        <div class="modal-dialog">
                                    <div class="modal-content">
                                    </div>
                          </div>
                     </div>
                <!--End Modal -->

        </div>
    </div>
</div>

schapp/templates/schapp/teachers/student-details.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

{% load static %}
<link href="{% static 'schapp/teacher/css/custom.css' %}" rel="stylesheet" type="text/css">


<!--Javascript files -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script type="text/javascript" src="{% static 'schapp/teacher/js/teachers.js' %}"></script>


<div class="container">
    <div class="row">

        <!--Teacher info-->
        <div class="col-sm-2">
            <div class="panel panel-danger">
                <div class="panel-body">
                    <img src="{% static 'schapp/teacher/images/t.jpg' %}" class="img img-circle img-responsive" alt="No image to display" style="width: 150px;height: 150px;">

                    <div class="caption">
                        <h4>{{ student.name }}</h4>
                        <h5>{{ student.admission }}</h5>
                        <h6>{{ student.form }}</h6>
                        <a href="" class="btn btn-info btn-sm"><i class="fas fa-edit"></i> </a>
                    </div>
                </div>
            </div>
        </div>
        <!--End Teacher section-->

         <!--Student info-->
        <div class="col-sm-10">
            <ul class="nav nav-tabs" style="margin: 2px;">
                <li class="active"><a href="{% url 'schapp:form1' %}">Form 1</a> </li>
                <li><a href="">Form 2</a> </li>
                <li><a href="">Form 3</a> </li>
                <li><a href="">Form 4</a> </li>
            </ul>


            <div class="panel panel-danger">
                <div class="panel-body">
                    <a href="" class="btn btn-success btn-sm">Term 1</a>
                    <a href="" class="btn btn-info btn-sm">Term 2</a>
                    <a href="" class="btn btn-primary btn-sm">Term 3</a>
                    <a href="" class="btn btn-danger" style="float: right; margin: 2px;"><i class="fas fa-print fa"></i></a>
                    <button class="btn btn-info js-add-grade" data-url="{% url 'schapp:add-grade' student.pk %}" style="float: right;margin: 2px;">
                        <i class="fas fa-plus-circle"></i>
                    </button>


                <div class="table-responsive">
                    <table class="table table-condensed"  id="student-table" style="margin: 2px;">
                        <thead>
                        <tr>
                        <th>Subject</th>
                        <th>CAT/30</th>
                        <th>Exam/70</th>
                        <th>Total</th>
                        <th>Grade</th>
                        <th>Remarks</th>
                        <th>Teacher</th>
                        <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for s in student.grade_set.all %}
                        <tr>
                            <td>{{ s.subject }}</td>
                            <td>{% if s.cat %}{{ s.cat }}{% else %}-{% endif %}</td>
                            <td>{{ s.exam }}</td>
                            <td>{{ s.exam }}</td>
                            <td>{{ Grade }}</td>
                            <td>{{ s.remark }}</td>
                            <td>{{ s.subject.teacher }}</td>
                            <td>
                                <a href="" class="btn btn-info btn-sm">
                                    <i class="fas fa-edit"></i>
                                </a>
                            </td>

                         </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>


                </div>
            </div>
        </div>
    </div>
</div>