schapp/urls.py
from django.urls import path
from .views import teachers, students

app_name = 'schapp'

urlpatterns = [
    # Teacher psths
    path('students', teachers.StudentListView.as_view(), name='all-students'),
    path('form1', teachers.form1_students, name='form1'),
    path('form2', teachers.form2_students, name='form2'),
    path('form3', teachers.form3_students, name='form3'),
    path('form4', teachers.form4_students, name='form4'),
    path('(?P<pk>\d+)/', teachers.student_detail, name='student-detail'),
    path('add-student', teachers.add_student, name='add-student'),
    path('(?P<pk>\d+)/student-update/', teachers.update_student, name='update-student'),
    path('(?P<pk>\d+)/student-delete/', teachers.delete_student, name='delete-student'),
    path('(?P<pk>\d+)/add-grade', teachers.add_grade, name='add-grade'),

    # Student paths
    path('profile', students.student_profile, name='student-profile'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', include('schapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schapp/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
DEPARTMENT = (
    ('english', 'English'),
    ('maths', 'Maths'),
    ('swahili', 'Swahili'),
    ('Biology', 'Biology'),
    ('Chemistry', 'Chemistry'),
    ('Physics', 'Physics'),
    ('Humanities', 'Humanities'),
    ('Grp4/5', 'Grp4/5'),
)

CLASS = (
    ('form 1', 'Form 1'),
    ('form 2', 'Form 2'),
    ('form 3', 'Form 3'),
    ('form 4', 'Form 4'),
)

YEAR = (
    ('2018', '2018'),
    ('2019', '2019'),
    ('2020', '2020'),
    ('2021', '2021'),
    ('2022', '2022'),
    ('2023', '2023'),

)


class Student(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    admission = models.BigIntegerField(unique=True)
    form = models.CharField(choices=CLASS, default='Form 1', max_length=6)
    house = models.CharField(max_length=50)
    club = models.CharField(max_length=50)
    #passport = models.ImageField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('schapp:teacher-index')


class Term(models.Model):
    name = models.CharField(max_length=10, unique=True)
    year = models.CharField(choices=YEAR, max_length=6, default=2018)

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=50)
    department = models.CharField(choices=DEPARTMENT, max_length=45, default='Maths')

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=20, unique=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT)
    department = models.CharField(choices=DEPARTMENT, max_length=45, default='Maths')

    def __str__(self):
        return self.name


class Grade(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    form = models.CharField(choices=CLASS, max_length=6, default='form 1')
    term = models.ForeignKey(Term, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT)
    cat = models.CharField(max_length=2)
    exam = models.CharField(max_length=3)
    remark = models.CharField(max_length=50)

    def __str__(self):
        return self.subject.name

schapp/forms.py
from django import forms
from .models import Student, Grade


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = '__all__'


class GradeForm(forms.ModelForm):

    class Meta:
        model = Grade
        exclude = ('student',)

schapp/views/students.py
from django.shortcuts import render
from django.views.generic import ListView
from ..models import Grade


def student_profile(request):
    grades = Grade.objects.all()
    return render(request, 'schapp/students/index.html', {'grades': grades})

schapp/views/teachers.py
from django.shortcuts import render, get_object_or_404
from ..forms import StudentForm, GradeForm
from ..models import Student, Subject
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView


class StudentListView(ListView):
    model = Student
    template_name = 'schapp/teachers/index.html'
    ordering = 'form'
    context_object_name = 'students'


def form1_students(request):
    students = Student.objects.filter(form='form 1')
    return render(request, 'schapp/teachers/index.html', {'students': students})


def form2_students(request):
    students = Student.objects.filter(form='form 2')
    return render(request, 'schapp/teachers/index.html', {'students': students})


def form3_students(request):
    students = Student.objects.filter(form='form 3')
    return render(request, 'schapp/teachers/index.html', {'students': students})


def form4_students(request):
    students = Student.objects.filter(form='form 4')
    return render(request, 'schapp/teachers/index.html', {'students': students})


# Saves student to DB
def save_student_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            students = Student.objects.filter(form='form 1')
            data['html_student_list'] = render_to_string('schapp/teachers/includes/partial-student-list.html',
                                                         {'students': students})
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


# Partial to re-use
def add_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
    else:
        form = StudentForm()
    return save_student_form(request, form, 'schapp/teachers/includes/partial-student-add.html')


def update_student(request, pk):
    s = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        form = StudentForm(request.POST, instance=s)
    else:
        form = StudentForm(instance=s)
    return save_student_form(request, form, 'schapp/teachers/includes/partial-student-update.html')


def delete_student(request, pk):
    s = get_object_or_404(Student, pk=pk)
    data = dict()
    if request.method == 'POST':
        s.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        students = Student.objects.filter(form='form 1')
        data['html_student_list'] = render_to_string('schapp/teachers/includes/partial-student-list.html', {
            'students': students
        })
    else:
        context = {'s': s}
        data['html_form'] = render_to_string('schapp/teachers/includes/partial-student-delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)


def save_grade_form(request, form, template_name, student):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            grade = form.save(commit=False)
            grade.student = student
            grade.save()
            data['form_is_valid'] = True
            students = Student.objects.all()
            data['html_student_list'] = render_to_string('schapp/teachers/includes/partial-student-list.html',
                                                         {'students': students})
        else:
            data['form_is_valid'] = False
    context = {'form': form, 'student': student}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def add_grade(request, pk):
    student = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        form = GradeForm(request.POST)
    else:
        form = GradeForm(instance=student.grade_set.first())
    return save_grade_form(request, form, 'schapp/teachers/includes/partial-grade-add.html', student)


"""
def add_grade(request, pk):
    student = get_object_or_404(Student, pk=pk)
    data = dict()
    if request.method == 'POST':
        form = GradeForm(request.POST or None)
        if form.is_valid():
            grade = form.save(commit=False)
            grade.student = student
            grade.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = GradeForm()
    context = {'form': form, 'student': student}
    data['html_form'] = render_to_string('schapp/teachers/includes/partial-grade-add.html',
                                         context, request=request)
    return JsonResponse(data)
"""


def student_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    subjects = Subject.objects.all()
    return render(request, 'schapp/teachers/student-details.html', {'student': student, 'subjects': subjects})

schapp/templates/schapp/teachers/includes/partial-grade-add.html
<form class="js-grade-form" method="post" action="{% url 'schapp:add-grade' student.pk %}">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Enter Student Scores:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">x</button>
    </div>
    <div class="modal-body">
        {% include 'schapp/teachers/includes/partial-grade-form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-info">Update</button>
    </div>
</form>

schapp/templates/schapp/teachers/includes/partial-grade-form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" %}
        {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}

schapp/templates/schapp/teachers/includes/partial-student-add.html
<form class="js-student-add-form" method="post" action="{% url 'schapp:add-student' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title text-primary">Add Student</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
     <div class="modal-body">
        {% include 'schapp/teachers/includes/partial-student-form.html' %}
     </div>
        <div class="modal-footer">
        <button type="submit" class="btn btn-info">Submit</button>
        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
    </div>
</form>

schapp/templates/schapp/teachers/includes/partial-student-delete.html
<form method="post" action="{% url 'schapp:delete-student' s.pk %}" class="js-student-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title" style="font-family: 'Helvetica Neue';">Confirm Student Deletion</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead" style="font-family: Roboto, sans-serif;">Are you sure you want to delete the student <strong>{{ s.name }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete</button>
    </div>
</form>

schapp/templates/schapp/teachers/includes/partial-student-form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" %}
        {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}

schapp/templates/schapp/teachers/includes/partial-student-list.html
{% for s in students %}
<tr>
    <td>{{ s.name }}</td>
    <td>{{ s.age }}</td>
    <td>{{ s.admission }}</td>
    <td>{{ s.form }}</td>
    <td>{{ s.house }}</td>
    <td>{{ s.club }}</td>

    <td>
       <button class="btn btn-info btn-sm js-add-grade" data-url="{% url 'schapp:add-grade' s.pk %}">
           <i class="fas fa-plus-circle"></i>
       </button>
    </td>

    <td>
        <a href="{% url 'schapp:student-detail' s.pk %}" class="btn btn-success btn-sm"><i class="fas fa-info"></i> </a>
    </td>

    <td>
        <button class="btn btn-primary btn-sm js-update-student" data-url="{% url 'schapp:update-student' s.pk %}">
            <i class="fas fa-edit"></i>
        </button>
        <button class="btn btn-danger btn-sm js-delete-student" data-url="{% url 'schapp:delete-student' s.pk %}">
            <i class="fas fa-trash"></i>
        </button>
    </td>


</tr>
{% endfor %}

schapp/templates/schapp/teachers/includes/partial-student-update.html
<form method="post" action="{% url 'schapp:update-student' form.instance.pk %}" class="js-student-update-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Update Student</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">x</button>
    </div>
    <div class="modal-body">
        {% include 'schapp/teachers/includes/partial-student-form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-info">Update</button>
    </div>
</form>